# Generated by Django 3.2 on 2023-10-31 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название города')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('temp', models.IntegerField(blank=True, null=True, verbose_name='Температура')),
                ('wind_speed', models.IntegerField(blank=True, null=True, verbose_name='Скорость ветра')),
                ('pressure_mm', models.IntegerField(blank=True, null=True, verbose_name='Давление')),
                ('request_time', models.DateTimeField(blank=True, null=True, verbose_name='Время запроса')),
                ('is_request', models.BooleanField(blank=True, null=True, verbose_name='Наличие запроса')),
            ],
        ),
    ]
