# Generated by Django 3.2 on 2023-11-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_weather_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телеграм chat_id')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='Состояние бота')),
            ],
        ),
    ]
